# Generated by Django 6.0.1 on 2026-01-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabIssue',
            fields=[
                ('lab_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_name', models.CharField(max_length=200)),
                ('form_name', models.CharField(max_length=200)),
                ('lab_category', models.CharField(max_length=200)),
                ('lab_date', models.DateField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=200)),
                ('test_description', models.CharField(blank=True, max_length=500, null=True)),
                ('issue', models.CharField(choices=[('Missing Lab Name', 'Missing Lab Name'), ('Missing Ranges', 'Missing Ranges'), ('Missing Units', 'Missing Units')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_issues', to='core.subject')),
            ],
            options={
                'verbose_name': 'Lab Issue',
                'verbose_name_plural': 'Lab Issues',
                'db_table': 'fact_lab_issue',
            },
        ),
        migrations.CreateModel(
            name='SAEDiscrepancy',
            fields=[
                ('sae_id', models.AutoField(primary_key=True, serialize=False)),
                ('discrepancy_id', models.CharField(max_length=100)),
                ('form_name', models.CharField(blank=True, max_length=200, null=True)),
                ('review_status_dm', models.CharField(blank=True, max_length=50, null=True)),
                ('action_status_dm', models.CharField(blank=True, max_length=50, null=True)),
                ('case_status', models.CharField(blank=True, max_length=50, null=True)),
                ('review_status_safety', models.CharField(blank=True, max_length=50, null=True)),
                ('action_status_safety', models.CharField(blank=True, max_length=50, null=True)),
                ('discrepancy_created_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sae_discrepancies', to='core.site')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sae_discrepancies', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sae_discrepancies', to='core.subject')),
            ],
            options={
                'verbose_name': 'SAE Discrepancy',
                'verbose_name_plural': 'SAE Discrepancies',
                'db_table': 'fact_sae_discrepancy',
                'unique_together': {('discrepancy_id', 'subject')},
            },
        ),
    ]
