# Generated by Django 6.0.1 on 2026-02-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labissue',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_issues', to='core.site'),
        ),
        migrations.AddField(
            model_name='labissue',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_issues', to='core.study'),
        ),
        migrations.AddField(
            model_name='saediscrepancy',
            name='resolution_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', help_text='Current resolution status', max_length=50),
        ),
        migrations.AddIndex(
            model_name='saediscrepancy',
            index=models.Index(fields=['site', 'resolution_status'], name='fact_sae_di_site_id_6881d4_idx'),
        ),
    ]
