# Generated by Django 6.0.1 on 2026-01-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformantEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(help_text="Type of non-conformance (e.g., 'Out of range', 'Missing required')", max_length=200)),
                ('severity', models.CharField(help_text='Severity: Low, Medium, High', max_length=50)),
                ('status', models.CharField(help_text='Status: Open, Resolved, Overridden', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of non-conformance', null=True)),
                ('detected_date', models.DateField(help_text='Date non-conformance was detected')),
                ('resolution_date', models.DateField(blank=True, help_text='Date issue was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformant_events', to='core.formpage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformant_events', to='core.subject')),
            ],
            options={
                'verbose_name': 'Non-Conformant Event',
                'verbose_name_plural': 'Non-Conformant Events',
                'db_table': 'fact_nonconformant_event',
            },
        ),
        migrations.CreateModel(
            name='PISignatureStatus',
            fields=[
                ('signature_id', models.AutoField(primary_key=True, serialize=False)),
                ('signed_by', models.CharField(blank=True, help_text='PI username who signed', max_length=200, null=True)),
                ('signed_date', models.DateField(blank=True, help_text='Date signature was completed', null=True)),
                ('status', models.CharField(help_text='Signature status: Pending, Signed', max_length=50)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of required signatures completed (0-100)', max_digits=5)),
                ('signature_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for PI signature event', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_signatures', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_signatures', to='core.subject')),
            ],
            options={
                'verbose_name': 'PI Signature Status',
                'verbose_name_plural': 'PI Signature Statuses',
                'db_table': 'fact_pi_signature_status',
            },
        ),
        migrations.CreateModel(
            name='ProtocolDeviation',
            fields=[
                ('deviation_id', models.AutoField(primary_key=True, serialize=False)),
                ('deviation_type', models.CharField(help_text='Type of protocol deviation', max_length=200)),
                ('status', models.CharField(help_text='Status: Open, Under Review, Resolved', max_length=50)),
                ('severity', models.CharField(blank=True, help_text='Severity: Minor, Major, Critical', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of deviation', null=True)),
                ('deviation_date', models.DateField(help_text='Date deviation occurred')),
                ('resolution_date', models.DateField(blank=True, help_text='Date deviation was resolved', null=True)),
                ('ai_severity_assessment', models.TextField(blank=True, help_text='AI-generated severity assessment and recommendations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_deviations', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_deviations', to='core.subject')),
            ],
            options={
                'verbose_name': 'Protocol Deviation',
                'verbose_name_plural': 'Protocol Deviations',
                'db_table': 'fact_protocol_deviation',
            },
        ),
        migrations.CreateModel(
            name='SDVStatus',
            fields=[
                ('sdv_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdv_date', models.DateField(blank=True, help_text='Date SDV was performed', null=True)),
                ('status', models.CharField(help_text='SDV status: Pending, In Progress, Complete', max_length=50)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of forms SDV-verified (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_records', to='core.site')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_records', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_records', to='core.subject')),
            ],
            options={
                'verbose_name': 'SDV Status',
                'verbose_name_plural': 'SDV Statuses',
                'db_table': 'fact_sdv_status',
            },
        ),
        migrations.CreateModel(
            name='MissingPage',
            fields=[
                ('missing_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_name', models.CharField(help_text='Visit where page is missing', max_length=200)),
                ('page_name', models.CharField(help_text='Name of missing CRF page', max_length=200)),
                ('form_details', models.CharField(blank=True, help_text='Additional form details from source report', max_length=500, null=True)),
                ('visit_date', models.DateField(blank=True, help_text='Visit date when page was expected', null=True)),
                ('days_missing', models.IntegerField(default=0, help_text='Number of days page has been missing (urgency metric)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_pages', to='core.subject')),
            ],
            options={
                'verbose_name': 'Missing Page',
                'verbose_name_plural': 'Missing Pages',
                'db_table': 'fact_missing_page',
                'ordering': ['-days_missing'],
                'indexes': [models.Index(fields=['subject', 'days_missing'], name='fact_missin_subject_bf362d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissingVisit',
            fields=[
                ('missing_visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_name', models.CharField(help_text="Name of missing visit (e.g., 'Week 4', 'Month 6')", max_length=200)),
                ('projected_date', models.DateField(help_text='Date visit was originally projected/scheduled')),
                ('days_outstanding', models.IntegerField(default=0, help_text='Number of days past projected date (urgency metric)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_visits', to='core.subject')),
            ],
            options={
                'verbose_name': 'Missing Visit',
                'verbose_name_plural': 'Missing Visits',
                'db_table': 'fact_missing_visit',
                'ordering': ['-days_outstanding'],
                'indexes': [models.Index(fields=['subject', 'days_outstanding'], name='fact_missin_subject_aae44c_idx')],
                'unique_together': {('subject', 'visit_name')},
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, help_text='EDC folder name', max_length=200, null=True)),
                ('form_name', models.CharField(help_text='EDC form name where query exists', max_length=200)),
                ('field_oid', models.CharField(blank=True, help_text='Field OID (unique field identifier in EDC)', max_length=200, null=True)),
                ('log_number', models.CharField(blank=True, help_text='Query log number from EDC system', max_length=100, null=True)),
                ('query_status', models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], help_text='Current query status', max_length=50)),
                ('action_owner', models.CharField(choices=[('Site', 'Site'), ('CRA', 'CRA'), ('DM', 'Data Management'), ('Sponsor', 'Sponsor')], help_text='Who is responsible for resolving this query', max_length=100)),
                ('marking_group_name', models.CharField(blank=True, help_text='Query marking group (query type categorization)', max_length=200, null=True)),
                ('query_open_date', models.DateField(help_text='Date query was opened')),
                ('query_response_date', models.DateField(blank=True, help_text='Date site responded to query', null=True)),
                ('visit_date', models.DateField(blank=True, help_text='Visit date related to this query', null=True)),
                ('days_since_open', models.IntegerField(default=0, help_text='Number of days query has been open (for SLA tracking)')),
                ('days_since_response', models.IntegerField(blank=True, help_text='Days since site responded (waiting DM closure)', null=True)),
                ('suggested_response', models.TextField(blank=True, help_text='AI-generated suggested response (GenAI Orchestrator)', null=True)),
                ('resolution_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for query resolution event', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, help_text='Form page where query was raised', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.formpage')),
                ('subject', models.ForeignKey(help_text='Subject this query belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.subject')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'fact_query_event',
                'ordering': ['-query_open_date'],
                'permissions': [('view_assigned_queries', 'Can view queries for assigned sites only')],
                'indexes': [models.Index(fields=['subject', 'query_status'], name='fact_query__subject_f06b2e_idx'), models.Index(fields=['query_status', 'action_owner'], name='fact_query__query_s_4a2267_idx'), models.Index(fields=['action_owner', 'query_open_date'], name='fact_query__action__6a5201_idx')],
            },
        ),
    ]
