# Generated by Django 6.0.1 on 2026-02-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRFEvent',
            fields=[
                ('crf_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('sign', 'Sign'), ('unsign', 'Unsign')], help_text='Type of CRF event', max_length=20)),
                ('event_time', models.DateTimeField(help_text='When the event occurred')),
                ('folder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('page_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRF Event',
                'verbose_name_plural': 'CRF Events',
                'db_table': 'fact_crf_event',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='OpenIssueSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_query_count', models.IntegerField(default=0)),
                ('missing_page_count', models.IntegerField(default=0)),
                ('missing_visit_count', models.IntegerField(default=0)),
                ('sae_discrepancy_count', models.IntegerField(default=0)),
                ('protocol_deviation_count', models.IntegerField(default=0)),
                ('total_open_issue_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Open Issue Summary',
                'verbose_name_plural': 'Open Issue Summaries',
                'db_table': 'fact_open_issue_summary',
            },
        ),
        migrations.AddField(
            model_name='missingpage',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this missing page has been resolved'),
        ),
        migrations.AddField(
            model_name='missingpage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_pages', to='core.site'),
        ),
        migrations.AddField(
            model_name='missingpage',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_pages', to='core.study'),
        ),
        migrations.AddField(
            model_name='missingpage',
            name='subject_status',
            field=models.CharField(blank=True, help_text='Subject status at time of missing page', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='missingvisit',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Whether this missing visit has been resolved'),
        ),
        migrations.AddField(
            model_name='missingvisit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_visits', to='core.site'),
        ),
        migrations.AddField(
            model_name='missingvisit',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_visits', to='core.study'),
        ),
        migrations.AddField(
            model_name='query',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code (denormalized from site)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_iters',
            field=models.IntegerField(blank=True, help_text='Number of query iterations/reopens', null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_repair_date',
            field=models.DateField(blank=True, help_text='Date when query was repaired/fixed', null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='region',
            field=models.CharField(blank=True, help_text='Region (denormalized from country)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this query belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.site'),
        ),
        migrations.AddField(
            model_name='query',
            name='site_number',
            field=models.CharField(blank=True, help_text='Site number (denormalized from site)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='study',
            field=models.ForeignKey(blank=True, help_text='Parent study', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.study'),
        ),
        migrations.AddField(
            model_name='query',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='Visit this query belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.visit'),
        ),
        migrations.AddIndex(
            model_name='missingpage',
            index=models.Index(fields=['site', 'is_resolved'], name='fact_missin_site_id_5feb00_idx'),
        ),
        migrations.AddIndex(
            model_name='missingvisit',
            index=models.Index(fields=['site', 'is_resolved'], name='fact_missin_site_id_8f9c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['study', 'query_status'], name='fact_query__study_i_70298a_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['site', 'query_status'], name='fact_query__site_id_0a3f76_idx'),
        ),
        migrations.AddField(
            model_name='crfevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crf_events', to='core.site'),
        ),
        migrations.AddField(
            model_name='crfevent',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf_events', to='core.study'),
        ),
        migrations.AddField(
            model_name='crfevent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crf_events', to='core.subject'),
        ),
        migrations.AddField(
            model_name='openissuesummary',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_issue_summaries', to='core.site'),
        ),
        migrations.AddField(
            model_name='openissuesummary',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_issue_summaries', to='core.study'),
        ),
        migrations.AddField(
            model_name='openissuesummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_issue_summary', to='core.subject'),
        ),
        migrations.AddIndex(
            model_name='crfevent',
            index=models.Index(fields=['study', 'event_type'], name='fact_crf_ev_study_i_5b27ce_idx'),
        ),
        migrations.AddIndex(
            model_name='crfevent',
            index=models.Index(fields=['subject', 'event_time'], name='fact_crf_ev_subject_e2fa44_idx'),
        ),
        migrations.AddIndex(
            model_name='openissuesummary',
            index=models.Index(fields=['study', 'total_open_issue_count'], name='fact_open_i_study_i_037181_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openissuesummary',
            unique_together={('study', 'subject')},
        ),
    ]
