# Generated by Django 6.0.1 on 2026-01-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQIWeightConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DQI Weight Configuration',
                'verbose_name_plural': 'DQI Weight Configurations',
                'db_table': 'dqi_weight_config',
            },
        ),
        migrations.CreateModel(
            name='CleanPatientStatus',
            fields=[
                ('clean_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_clean', models.BooleanField(default=False)),
                ('has_missing_visits', models.BooleanField(default=False)),
                ('missing_visits_count', models.IntegerField(default=0)),
                ('has_missing_pages', models.BooleanField(default=False)),
                ('missing_pages_count', models.IntegerField(default=0)),
                ('has_open_queries', models.BooleanField(default=False)),
                ('open_queries_count', models.IntegerField(default=0)),
                ('has_non_conformant', models.BooleanField(default=False)),
                ('non_conformant_count', models.IntegerField(default=0)),
                ('has_sae_discrepancies', models.BooleanField(default=False)),
                ('sae_discrepancy_count', models.IntegerField(default=0)),
                ('sdv_incomplete', models.BooleanField(default=False)),
                ('sdv_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pi_signature_incomplete', models.BooleanField(default=False)),
                ('pi_signature_completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('has_coding_backlog', models.BooleanField(default=False)),
                ('coding_uncoded_count', models.IntegerField(default=0)),
                ('has_edrr_issues', models.BooleanField(default=False)),
                ('edrr_open_issue_count', models.IntegerField(default=0)),
                ('blockers_json', models.TextField(blank=True, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_status', to='core.subject')),
            ],
            options={
                'verbose_name': 'Clean Patient Status',
                'verbose_name_plural': 'Clean Patient Statuses',
                'db_table': 'mart_clean_patient_status',
            },
        ),
        migrations.CreateModel(
            name='DQIScoreSite',
            fields=[
                ('dqi_site_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_subjects', models.IntegerField(default=0)),
                ('clean_subjects', models.IntegerField(default=0)),
                ('clean_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite_dqi_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_band', models.CharField(default='Low', max_length=20)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dqi_score', to='core.site')),
            ],
            options={
                'verbose_name': 'DQI Score (Site)',
                'verbose_name_plural': 'DQI Scores (Site)',
                'db_table': 'mart_dqi_score_site',
            },
        ),
        migrations.CreateModel(
            name='DQIScoreStudy',
            fields=[
                ('dqi_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_sites', models.IntegerField(default=0)),
                ('total_subjects', models.IntegerField(default=0)),
                ('clean_subjects', models.IntegerField(default=0)),
                ('clean_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite_dqi_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('readiness_status', models.CharField(default='Not Ready', max_length=50)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dqi_score', to='core.study')),
            ],
            options={
                'verbose_name': 'DQI Score (Study)',
                'verbose_name_plural': 'DQI Scores (Study)',
                'db_table': 'mart_dqi_score_study',
            },
        ),
        migrations.CreateModel(
            name='DQIScoreSubject',
            fields=[
                ('dqi_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('sae_unresolved_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('missing_visits_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('missing_pages_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('open_queries_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('non_conformant_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sdv_incomplete_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pi_signature_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('coding_backlog_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('edrr_issue_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite_dqi_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_band', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dqi_score', to='core.subject')),
            ],
            options={
                'verbose_name': 'DQI Score (Subject)',
                'verbose_name_plural': 'DQI Scores (Subject)',
                'db_table': 'mart_dqi_score_subject',
            },
        ),
    ]
