# Generated by Django 6.0.1 on 2026-01-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingItem',
            fields=[
                ('coding_id', models.AutoField(primary_key=True, serialize=False)),
                ('dictionary_name', models.CharField(choices=[('MedDRA', 'MedDRA'), ('WHODD', 'WHODD')], max_length=50)),
                ('dictionary_version', models.CharField(blank=True, max_length=50, null=True)),
                ('form_oid', models.CharField(max_length=200)),
                ('logline', models.CharField(blank=True, max_length=200, null=True)),
                ('field_oid', models.CharField(blank=True, max_length=200, null=True)),
                ('coding_status', models.CharField(max_length=50)),
                ('require_coding', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_items', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_items', to='core.subject')),
            ],
            options={
                'verbose_name': 'Coding Item',
                'verbose_name_plural': 'Coding Items',
                'db_table': 'fact_coding_item',
            },
        ),
        migrations.CreateModel(
            name='InactivatedRecord',
            fields=[
                ('inactivated_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('form_name', models.CharField(max_length=200)),
                ('data_on_form', models.CharField(blank=True, max_length=500, null=True)),
                ('record_position', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_action', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivated_records', to='core.subject')),
            ],
            options={
                'verbose_name': 'Inactivated Record',
                'verbose_name_plural': 'Inactivated Records',
                'db_table': 'fact_inactivated_record',
            },
        ),
        migrations.CreateModel(
            name='EDRROpenIssue',
            fields=[
                ('edrr_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_open_issue_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edrr_issues', to='core.study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edrr_issues', to='core.subject')),
            ],
            options={
                'verbose_name': 'EDRR Open Issue',
                'verbose_name_plural': 'EDRR Open Issues',
                'db_table': 'fact_edrr_open_issue',
                'unique_together': {('study', 'subject')},
            },
        ),
    ]
