# Generated by Django 6.0.1 on 2026-02-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('medical_coding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inactivatedrecord',
            name='data_on_form',
        ),
        migrations.AddField(
            model_name='inactivatedrecord',
            name='record_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inactivatedrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactivated_records', to='core.site'),
        ),
        migrations.AddField(
            model_name='inactivatedrecord',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactivated_records', to='core.study'),
        ),
        migrations.AlterField(
            model_name='codingitem',
            name='form_oid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
