# Generated by Django 6.0.1 on 2026-01-30 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text="ISO country code or custom code (e.g., 'IND', 'USA')", max_length=10)),
                ('country_name', models.CharField(help_text="Full country name (e.g., 'India', 'United States')", max_length=200)),
                ('region', models.CharField(help_text="Geographic region (e.g., 'APAC', 'EMEA', 'Americas')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'dim_country',
                'ordering': ['region', 'country_name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.CharField(help_text="Unique study identifier (e.g., 'Study_1', 'NYS-GRE-293')", max_length=100, primary_key=True, serialize=False)),
                ('study_name', models.CharField(help_text='Full name of the clinical trial study', max_length=500)),
                ('region', models.CharField(blank=True, help_text="Primary geographic region (e.g., 'APAC', 'EMEA', 'Americas')", max_length=100, null=True)),
                ('status', models.CharField(default='Active', help_text='Study status: Active, Completed, On-Hold', max_length=50)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this study snapshot was created')),
                ('blockchain_hash', models.CharField(blank=True, help_text='SHA-256 hash of study data for blockchain verification', max_length=64, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash where study creation was recorded', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'db_table': 'dim_study',
                'ordering': ['study_id'],
                'permissions': [('view_study_leadership', 'Can view study as leadership'), ('view_study_cra', 'Can view study as CRA')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(help_text='Unique site identifier: {study_id}_{site_number}', max_length=100, primary_key=True, serialize=False)),
                ('site_number', models.CharField(help_text="Site number within study (e.g., '101', '102')", max_length=50)),
                ('site_name', models.CharField(blank=True, help_text='Full site name or hospital name (optional)', max_length=500, null=True)),
                ('status', models.CharField(default='Active', help_text='Site status: Active, Inactive, Closed', max_length=50)),
                ('assigned_cra', models.CharField(blank=True, help_text='CRA username assigned to this site for RBAC', max_length=100, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(help_text='Country where site is located', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.country')),
                ('study', models.ForeignKey(help_text='Parent study', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.study')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'dim_site',
                'ordering': ['site_number'],
                'permissions': [('view_assigned_sites', 'Can view only assigned sites (CRA)')],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='study',
            field=models.ForeignKey(help_text='Parent study this country belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.study'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(help_text='Unique subject identifier: {study_id}_{subject_number}', max_length=100, primary_key=True, serialize=False)),
                ('subject_external_id', models.CharField(blank=True, help_text="External subject ID visible in source files (e.g., '0-005') - PSEUDONYMIZED", max_length=100, null=True)),
                ('subject_status', models.CharField(choices=[('Screened', 'Screened'), ('Enrolled', 'Enrolled'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Screen Failed', 'Screen Failed'), ('Suspended', 'Suspended')], help_text='Current subject lifecycle status', max_length=50)),
                ('enrollment_date', models.DateField(blank=True, help_text='Date subject was enrolled (if applicable)', null=True)),
                ('latest_visit', models.CharField(blank=True, help_text='Most recent visit completed (for quick reference)', max_length=200, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('enrollment_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(help_text='Site where subject is enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.site')),
                ('study', models.ForeignKey(help_text='Parent study', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.study')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'dim_subject',
                'ordering': ['site', 'subject_external_id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_name', models.CharField(help_text="Protocol-defined visit name (e.g., 'Screening', 'Week 4')", max_length=200)),
                ('visit_date', models.DateField(blank=True, help_text='Actual visit date (when visit occurred)', null=True)),
                ('projected_date', models.DateField(blank=True, help_text='Projected/scheduled visit date', null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', help_text='Visit status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject this visit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.subject')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'dim_visit',
                'ordering': ['subject', 'projected_date', 'visit_date'],
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, help_text='EDC folder name (top level)', max_length=200, null=True)),
                ('form_name', models.CharField(help_text='EDC form name', max_length=200)),
                ('form_oid', models.CharField(blank=True, help_text='EDC form OID (object identifier)', max_length=200, null=True)),
                ('page_name', models.CharField(blank=True, help_text='EDC page name (if form has multiple pages)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Locked', 'Locked'), ('Signed', 'Signed'), ('Frozen', 'Frozen')], default='Draft', help_text='Current data entry status', max_length=50)),
                ('lock_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('signature_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.ForeignKey(help_text='Visit this form/page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='form_pages', to='core.visit')),
            ],
            options={
                'verbose_name': 'Form Page',
                'verbose_name_plural': 'Form Pages',
                'db_table': 'dim_form_page',
                'ordering': ['visit', 'folder_name', 'form_name', 'page_name'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['assigned_cra', 'status'], name='dim_site_assigne_b54b4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('study', 'country_code')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['site', 'subject_status'], name='dim_subject_site_id_685189_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_status'], name='dim_subject_subject_f4b4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['enrollment_date'], name='dim_subject_enrollm_da2fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['subject', 'status'], name='dim_visit_subject_6ed310_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('subject', 'visit_name')},
        ),
        migrations.AddIndex(
            model_name='formpage',
            index=models.Index(fields=['visit', 'status'], name='dim_form_pa_visit_i_05fa28_idx'),
        ),
    ]
