# Generated by Django 6.0.1 on 2026-01-30 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, help_text='SHA-256 hash of transaction (simulates blockchain tx hash)', max_length=64, unique=True)),
                ('block_number', models.IntegerField(help_text='Block number in chain')),
                ('event_type', models.CharField(choices=[('DQI_COMPUTED', 'DQI Score Computed'), ('CLEAN_STATUS_UPDATED', 'Clean Status Updated'), ('QUERY_RESOLVED', 'Query Resolved'), ('SAE_REPORTED', 'SAE Reported'), ('DATABASE_LOCK', 'Database Lock Initiated'), ('STUDY_COMPLETION', 'Study Completion'), ('DATA_FREEZE', 'Data Freeze'), ('PROTOCOL_DEVIATION', 'Protocol Deviation Logged')], help_text='Type of clinical trial event', max_length=100)),
                ('event_description', models.TextField(help_text='Human-readable description of event')),
                ('data_hash', models.CharField(help_text='SHA-256 hash of data snapshot', max_length=64)),
                ('data_snapshot', models.JSONField(help_text='Snapshot of data at time of event (for verification)')),
                ('previous_hash', models.CharField(blank=True, help_text='Hash of previous transaction (blockchain chain)', max_length=64, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When transaction was recorded')),
                ('recorded_by', models.CharField(help_text='User or system that recorded this event', max_length=100)),
                ('verified', models.BooleanField(default=False, help_text='Whether transaction has been verified')),
                ('verification_timestamp', models.DateTimeField(blank=True, help_text='When transaction was verified', null=True)),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-block_number', '-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='blockchain__event_t_520752_idx'), models.Index(fields=['block_number'], name='blockchain__block_n_4f2665_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Type of entity (Subject, Site, Study, Query, etc.)', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the entity', max_length=100)),
                ('action', models.CharField(help_text='Action performed', max_length=100)),
                ('changes', models.JSONField(blank=True, help_text='Before/after changes', null=True)),
                ('performed_by', models.CharField(help_text='User who performed action', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='blockchain.blockchaintransaction')),
            ],
            options={
                'db_table': 'blockchain_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='blockchain__entity__818886_idx'), models.Index(fields=['-timestamp'], name='blockchain__timesta_9e99df_idx')],
            },
        ),
    ]
